"""
waf_detector.py — WAF / CDN / reverse-proxy fingerprinting.

No auth required. Sends a probe request to each host and fingerprints the
response headers against known WAF/CDN signatures. Also detects rate
limiting (429 + Retry-After header).

Signatures from: Cloudflare, Akamai, AWS WAF/CloudFront, Sucuri, Imperva,
F5 BIG-IP, Fortinet FortiWeb, Barracuda, ModSecurity, NAXSI, LiteSpeed,
Varnish, Fastly, CloudFront, Azure Front Door, Google Cloud Armor.

Config keys (under `waf.*`):
  timeout: per-request timeout (default 10)
  max_hosts: max hosts to probe (default 100)
  probe_path: path to probe (default /)
"""

import asyncio
import re
from typing import Dict, List, Optional, Any, Tuple
from urllib.parse import urlparse

import aiohttp

from app.utils.logger import get_logger

logger = get_logger()

_WAF_SIGNATURES = [
    {
        'name': 'Cloudflare',
        'headers': {
            'server': r'^cloudflare$',
            'cf-ray': r'.',
            'cf-cache-status': r'.',
            'cf-request-id': r'.',
            '__cfduid': r'.',
            'cf-chl-bypass': r'.',
            'cf-chl-out': r'.',
            'cf-mitigated': r'.',
        },
        'cookies': {'__cfduid': '.', 'cf_clearance': '.', '__cf_bm': '.'},
        'status_codes': {403, 503},
        'body_patterns': [r'cf-browser-verification', r'cf-challenge',
                          r'Checking your browser', r'DDoS protection by Cloudflare',
                          r'Please enable cookies', r'Attention Required'],
    },
    {
        'name': 'Akamai',
        'headers': {
            'x-akamai-transformed': r'.',
            'x-akamai-request-id': r'.',
            'x-akamai-edge': r'.',
            'x-akamai-stats': r'.',
            'server': r'AkamaiGHost',
            'x-akamai-config-diff': r'.',
            'x-akamai-session-info': r'.',
        },
        'cookies': {'ak_bmsc': '.', 'akamai_ru': '.', 'bm_sz': '.', '_abck': '.'},
        'status_codes': {403},
        'body_patterns': [r'Reference #\d+\.\w+', r'Access Denied',
                          r'akamai\.com', r'You don\'t have permission'],
    },
    {
        'name': 'AWS CloudFront / WAF',
        'headers': {
            'x-amz-cf-id': r'.',
            'x-amz-cf-pop': r'.',
            'x-amzn-requestid': r'.',
            'x-amzn-waf-action': r'.',
            'x-amz-waf-action': r'.',
            'x-amzn-errortype': r'.',
            'server': r'CloudFront',
            'x-cache': r'.',
            'via': r'.*cloudfront',
        },
        'cookies': {'aws-waf-token': '.', 'awsalbcors': '.', 'awsalb': '.'},
        'status_codes': {403, 503},
        'body_patterns': [r'Request blocked', r'Generated by cloudfront',
                          r'CloudFront', r'AWS WAF', r'AWSALB'],
    },
    {
        'name': 'Sucuri',
        'headers': {
            'x-sucuri-id': r'.',
            'x-sucuri-cache': r'.',
            'x-sucuri-block': r'.',
            'server': r'Sucuri/Cloudproxy',
        },
        'cookies': {'sucuri_cloudproxy_uuid': '.', 'sucuri_privacy': '.'},
        'status_codes': {403},
        'body_patterns': [r'Sucuri WebSite Firewall', r'Access Denied - Sucuri Website Firewall',
                          r'CloudProxy - Sucuri'],
    },
    {
        'name': 'Imperva / Incapsula',
        'headers': {
            'x-iinfo': r'.',
            'x-cdn': r'Incapsula',
            'x-cdn-request-id': r'.',
            'x-request-id': r'.',
        },
        'cookies': {'incap_ses_': '.', 'visid_incap_': '.', 'nlbi_': '.',
                    'reese84': '.', 'reese': '.', '_imp_apg_r_': '.'},
        'status_codes': {403},
        'body_patterns': [r'Incapsula incident', r'Imperva', r'incap_ses',
                          r'Request unsuccessful', r'Cached by Incapsula'],
    },
    {
        'name': 'F5 BIG-IP',
        'headers': {
            'server': r'BigIP',
            'x-cnection': r'.',
            'x-wa-info': r'.',
            'x-pv-info': r'.',
        },
        'cookies': {
            'BIGipServer': '.', 'BIGipServerPool': '.', 'TS': '.',
            'LastMRH_Session': '.', 'MRHSession': '.', 'F5_ST': '.',
            'F5_fullWT': '.', 'F5_Node': '.',
        },
        'status_codes': {403},
        'body_patterns': [r'BIG-IP', r'F5 Networks', r'The requested URL was rejected'],
    },
    {
        'name': 'Fortinet FortiWeb',
        'headers': {
            'server': r'FortiWeb',
            'x-fortiweb-session': r'.',
            'x-fortiweb-id': r'.',
        },
        'cookies': {'cookiesession1': '.', 'FORTIWAFSID': '.'},
        'status_codes': {403},
        'body_patterns': [r'FortiWeb', r'FortiGuard', r'Web Application Firewall'],
    },
    {
        'name': 'Barracuda WAF',
        'headers': {
            'server': r'Barracuda',
            'x-barracuda': r'.',
        },
        'cookies': {'barra_counter_session': '.', 'BNI__BARRACUDA_LB_COOKIE': '.',
                    'BNI_persistence': '.', 'BNI_BARRACUDA_LB_COOKIE': '.'},
        'status_codes': {403},
        'body_patterns': [r'Barracuda', r'barracuda\.com'],
    },
    {
        'name': 'ModSecurity',
        'headers': {
            'server': r'Apache',
        },
        'cookies': {},
        'status_codes': {403, 406},
        'body_patterns': [r'ModSecurity', r'mod_security', r'This error was generated by Mod_Security',
                          r'Not Acceptable!', r'An appropriate representation of the requested'],
    },
    {
        'name': 'LiteSpeed',
        'headers': {
            'server': r'LiteSpeed',
            'x-litespeed-cache': r'.',
            'x-lsadc-cache': r'.',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Varnish',
        'headers': {
            'x-varnish': r'.',
            'x-varnish-cache': r'.',
            'via': r'.*varnish',
            'x-cache': r'.',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Fastly',
        'headers': {
            'x-served-by': r'.',
            'x-cache': r'.*,\s*\w+',
            'x-cache-hits': r'.',
            'x-timer': r'.',
            'fastly-ff': r'.',
            'fastly-request-id': r'.',
            'via': r'.*Fastly',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Azure Front Door',
        'headers': {
            'x-azure-ref': r'.',
            'x-azure-requestchain': r'.',
            'x-azure-fdid': r'.',
            'x-azure-socketip': r'.',
            'x-azure-externalip': r'.',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Google Cloud Armor',
        'headers': {},
        'cookies': {},
        'status_codes': {403, 429},
        'body_patterns': [r'Google Cloud Armor', r'cloud armor'],
    },
    {
        'name': 'NAXSI (Nginx)',
        'headers': {
            'x-naxsi-sig': r'.',
        },
        'cookies': {},
        'status_codes': {403, 418},
        'body_patterns': [r'NAXSI', r'Blocked by NAXSI'],
    },
    {
        'name': 'Wordfence (WordPress)',
        'headers': {
            'x-wordfence': r'.',
        },
        'cookies': {'wfvt_': '.', 'wordfence_verifiedHuman': '.'},
        'status_codes': {403, 503},
        'body_patterns': [r'Wordfence', r'Generated by Wordfence',
                          r'blocked by Wordfence', r'Your access to this site'],
    },
    {
        'name': 'Reblaze',
        'headers': {
            'server': r'Reblaze Secure Web Gateway',
        },
        'cookies': {'rbzid': '.', 'rbz_sessionid': '.'},
        'status_codes': {403},
        'body_patterns': [r'Reblaze', r'Current session has been terminated'],
    },
    {
        'name': 'Distil Networks',
        'headers': {},
        'cookies': {'distil_': '.', 'distil_uu': '.', 'distil_ta': '.'},
        'status_codes': {403},
        'body_patterns': [r'Distil', r'distilnetworks'],
    },
    {
        'name': 'CacheWall / Varnish',
        'headers': {
            'via': r'.*Varnish',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Edgecast / Verizon',
        'headers': {
            'server': r'^(?:ECAcc|ECD|ECS)\b',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'StackPath',
        'headers': {
            'x-stackpath-id': r'.',
            'x-stackpath-edge': r'.',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Kinsta',
        'headers': {
            'x-kinsta-cache': r'.',
            'server': r'kinsta',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Pantheon',
        'headers': {
            'x-pantheon-styx-hostname': r'.',
            'x-styx-req-id': r'.',
            'server': r'Pantheon',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'WP Engine',
        'headers': {
            'x-wpengine': r'.',
            'x-wpe-backend': r'.',
            'x-wpe-request-id': r'.',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Netlify',
        'headers': {
            'server': r'Netlify',
            'x-nf-request-id': r'.',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Vercel',
        'headers': {
            'x-vercel-id': r'.',
            'x-vercel-cache': r'.',
            'server': r'Vercel',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Heroku',
        'headers': {
            'via': r'.*vegur',
            'x-heroku': r'.',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Fly.io',
        'headers': {
            'fly-request-id': r'.',
            'server': r'Fly/',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'BunnyCDN',
        'headers': {
            'cdn-cache': r'.',
            'cdn-cachedat': r'.',
            'cdn-edgestorageid': r'.',
            'cdn-pullzone': r'.',
            'cdn-requestcountrycode': r'.',
            'cdn-requestid': r'.',
            'cdn-status': r'.',
            'cdn-uid': r'.',
            'server': r'BunnyCDN',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'KeyCDN',
        'headers': {
            'x-cache': r'.',
            'x-cache-status': r'.',
            'x-edge-location': r'.',
            'server': r'keycdn',
        },
        'cookies': {},
        'status_codes': set(),
        'body_patterns': [],
    },
    {
        'name': 'Cloudflare Rate Limiting',
        'headers': {
            'retry-after': r'.',
        },
        'cookies': {},
        'status_codes': {429},
        'body_patterns': [],
    },
    {
        'name': 'Generic Rate Limiting',
        'headers': {
            'retry-after': r'.',
            'x-ratelimit-limit': r'.',
            'x-ratelimit-remaining': r'.',
            'x-ratelimit-reset': r'.',
        },
        'cookies': {},
        'status_codes': {429},
        'body_patterns': [],
    },
]


class WAFDetector:
    """Fingerprint WAF/CDN/proxy on targets."""

    def __init__(self, config: Optional[Dict] = None):
        config = config or {}
        cfg = config.get('waf', {}) if isinstance(config, dict) else {}
        self.timeout = int(cfg.get('timeout', 10))
        self.max_hosts = int(cfg.get('max_hosts', 100))
        self.probe_path = cfg.get('probe_path', '/')
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                          'AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36'
        }

    async def _probe(self, session: aiohttp.ClientSession,
                     url: str) -> Tuple[Dict, str, int]:
        """Probe a URL and return (response_headers, body, status)."""
        try:
            async with session.get(
                url, headers=self.headers,
                timeout=aiohttp.ClientTimeout(total=self.timeout),
                allow_redirects=True,
            ) as r:
                body = await r.text(errors='ignore')
                return dict(r.headers), body, r.status
        except Exception:
            return {}, '', -1

    def _fingerprint(self, headers: Dict, cookies: Dict, status: int,
                     body: str) -> List[Dict]:
        """Match response against WAF signatures."""
        findings = []
        header_keys = {k.lower() for k in headers}
        cookie_keys = {k.lower() for k in cookies}

        for sig in _WAF_SIGNATURES:
            matches = []

            for hdr, pattern in sig['headers'].items():
                if hdr.lower() in header_keys:
                    val = next((v for k, v in headers.items() if k.lower() == hdr.lower()), '')
                    if re.search(pattern, val, re.IGNORECASE):
                        matches.append(f'header:{hdr}={val[:80]}')

            for ck, pattern in sig['cookies'].items():
                if ck.lower() in cookie_keys:
                    val = next((v for k, v in cookies.items() if k.lower() == ck.lower()), '')
                    if pattern == '.' or re.search(pattern, val, re.IGNORECASE):
                        matches.append(f'cookie:{ck}')

            if sig['status_codes'] and status in sig['status_codes']:
                matches.append(f'status:{status}')

            for pat in sig['body_patterns']:
                if re.search(pat, body, re.IGNORECASE):
                    matches.append(f'body:{pat[:60]}')

            if matches:
                hdr_matches = [m for m in matches if m.startswith('header:') or m.startswith('cookie:')]
                if not hdr_matches:
                    continue
                findings.append({
                    'waf': sig['name'],
                    'evidence': matches[:4],
                    'confidence': 'high' if len(hdr_matches) >= 2 else 'medium',
                })

        if not findings:
            findings.append({
                'waf': 'None detected',
                'evidence': [],
                'confidence': 'low',
            })

        return findings

    def _parse_cookies(self, headers: Dict) -> Dict:
        """Parse Set-Cookie headers into a dict."""
        cookies = {}
        for key, val in headers.items():
            if key.lower() == 'set-cookie':
                parts = val.split(';')[0].strip()
                if '=' in parts:
                    ck, cv = parts.split('=', 1)
                    cookies[ck.strip()] = cv.strip()
        return cookies

    async def scan(self, urls: List[str]) -> Dict[str, Any]:
        """Scan hosts for WAF fingerprinting."""
        if not urls:
            return {'hosts': [], 'summary': {}}

        urls = urls[:self.max_hosts]
        connector = aiohttp.TCPConnector(ssl=False)
        results = []
        waf_counts = {}

        async with aiohttp.ClientSession(connector=connector) as session:
            for url in urls:
                try:
                    parsed = urlparse(url)
                    host = parsed.netloc or parsed.path.split('/')[0]
                    probe_url = f"{parsed.scheme or 'https'}://{host}{self.probe_path}"
                except Exception:
                    continue

                hdrs, body, status = await self._probe(session, probe_url)
                if status < 0:
                    continue

                cookies = self._parse_cookies(hdrs)
                fps = self._fingerprint(hdrs, cookies, status, body)

                server = hdrs.get('server', hdrs.get('Server', ''))
                via = hdrs.get('via', hdrs.get('Via', ''))

                result = {
                    'host': host,
                    'status': status,
                    'server': server,
                    'via': via,
                    'wafs': [f['waf'] for f in fps],
                    'primary_waf': fps[0]['waf'] if fps else 'None',
                    'evidence': fps[0].get('evidence', []) if fps else [],
                    'confidence': fps[0]['confidence'] if fps else 'low',
                    'headers': {k: v for k, v in list(hdrs.items())[:20]},
                }
                results.append(result)

                for f in fps:
                    waf_counts[f['waf']] = waf_counts.get(f['waf'], 0) + 1

        return {
            'hosts': results,
            'summary': {
                'total_probed': len(results),
                'waf_distribution': sorted(waf_counts.items(), key=lambda x: -x[1]),
                'protected': sum(1 for r in results if r['primary_waf'] != 'None detected'),
                'unprotected': sum(1 for r in results if r['primary_waf'] == 'None detected'),
            },
        }

    def scan_sync(self, urls: List[str]) -> Dict[str, Any]:
        try:
            return asyncio.run(self.scan(urls))
        except RuntimeError:
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as ex:
                return ex.submit(asyncio.run, self.scan(urls)).result()
        except Exception as e:
            logger.error(f"WAF scan failed: {e}")
            return {'hosts': [], 'summary': {}}


__all__ = ['WAFDetector']